import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1 },
  header: { paddingHorizontal: 20, paddingBottom: 24 },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 4,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitleWrap: { flex: 1 },
  headerTitle: { fontSize: 20, fontWeight: "800", letterSpacing: -0.4 },
  headerSub: { fontSize: 12, fontWeight: "500", marginTop: 1 },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  statusText: { fontSize: 12, fontWeight: "700" },

  scrollView: { marginTop: -12 },
  body: { padding: 16, gap: 14, paddingBottom: 32 },

  section: {
    borderRadius: 20,
    padding: 18,
    gap: 0,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.06)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 14,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 10,
  },
  infoIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  infoTextWrap: { flex: 1 },
  infoLabel: {
    fontSize: 11,
    fontWeight: "600",
    marginBottom: 2,
    letterSpacing: 0.2,
  },
  infoValue: { fontSize: 14, fontWeight: "600" },
  divider: { height: 1, marginHorizontal: -18 },

  categoryWrap: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  catChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  catText: { fontSize: 11, fontWeight: "600" },

  actionSection: { gap: 10, marginBottom: 8 },
  approveBtn: { borderRadius: 14 },
  approveBtnContent: { height: 52 },
  approveBtnLabel: { fontSize: 15, fontWeight: "700" },

  rejectCard: {
    borderRadius: 20,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.06)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  rejectTitle: { fontSize: 13, fontWeight: "700", marginBottom: 4 },
  rejectInput: { backgroundColor: "transparent" },
  rejectConfirmBtn: { borderRadius: 12 },
  rejectConfirmContent: { height: 48 },

  centered: { flex: 1, alignItems: "center", justifyContent: "center" },

  dialogScrollArea: { paddingHorizontal: 0 },
  dialogSection: { gap: 10, marginBottom: 10 },
  dialogSectionTitle: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  dialogInput: { backgroundColor: "transparent", marginBottom: 2 },
  dialogCategoryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  dialogCatTile: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1.5,
  },
  dialogCatText: { fontSize: 12, fontWeight: "600" },
  dialogErrorBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FEE2E2",
    borderRadius: 10,
    padding: 10,
    marginBottom: 4,
  },
  dialogErrorText: {
    fontSize: 12,
    color: "#DC2626",
    flex: 1,
    fontWeight: "500",
  },
});
