import { StyleSheet } from "react-native";
import { COLORS } from "../../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { paddingBottom: 24 },

  header: {
    paddingHorizontal: 20,
    paddingBottom: 36,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  headerGreeting: { fontSize: 13, fontWeight: "600" },
  headerTitle: {
    fontSize: 28,
    fontWeight: "bold",
    letterSpacing: -0.5,
    marginTop: 0,
    marginBottom: -2,
  },
  headerSubtitle: { fontSize: 12, fontWeight: "500" },
  locationBadge: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 4,
    marginTop: 4,
  },
  locationText: { fontSize: 13, fontWeight: "600" },

  searchBar: {
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    elevation: 0,
  },
  searchInput: { fontSize: 14 },

  scrollView: {
    marginTop: -20,
    backgroundColor: "transparent",
  },

  contentSheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 12,
    flex: 1,
  },
  sheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#E2E8F0",
    alignSelf: "center",
    marginBottom: 16,
  },

  statsRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    gap: 10,
    marginBottom: 8,
  },
  statCard: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 12,
    borderRadius: 12,
    borderLeftWidth: 3,
    gap: 2,
  },
  statValue: {
    fontSize: 15,
    fontWeight: "800",
    color: "#111827",
    marginTop: 4,
  },
  statLabel: { fontSize: 10, color: "#6B7280", fontWeight: "500" },

  section: { paddingHorizontal: 16, marginTop: 24 },
  lastSection: { marginBottom: 8 },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  sectionTitle: { fontSize: 17, fontWeight: "700", letterSpacing: -0.3 },
  seeAll: { fontSize: 13, fontWeight: "600" },
  updatedBadge: { flexDirection: "row", alignItems: "center", gap: 5 },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: COLORS.success,
  },
  updatedText: { fontSize: 12, color: COLORS.success, fontWeight: "600" },

  categoryScroll: { marginHorizontal: -16, paddingHorizontal: 16 },
  categoryItem: {
    alignItems: "center",
    marginRight: 12,
    padding: 12,
    borderRadius: 14,
    width: 80,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  categoryIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  categoryLabel: {
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
    lineHeight: 14,
  },

  priceCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 14,
    borderRadius: 14,
    marginBottom: 10,
  },
  priceCardLeft: { flex: 1 },
  materialName: { fontSize: 14, fontWeight: "700", marginBottom: 2 },
  brandName: { fontSize: 12, marginBottom: 4 },
  supplierCount: { flexDirection: "row", alignItems: "center", gap: 4 },
  supplierText: { fontSize: 11 },
  priceCardRight: { alignItems: "flex-end", gap: 4 },
  priceValue: { fontSize: 18, fontWeight: "800" },
  priceUnit: { fontSize: 11 },
  changeTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
  },
  changeText: { fontSize: 11, fontWeight: "700" },

  supplierCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    borderRadius: 14,
    marginBottom: 10,
    gap: 12,
  },
  supplierAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  supplierInitial: { fontSize: 18, fontWeight: "800" },
  supplierInfo: { flex: 1 },
  supplierNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 3,
  },
  supplierName: { fontSize: 14, fontWeight: "700" },
  supplierMeta: { flexDirection: "row", alignItems: "center", gap: 4 },
  supplierMetaText: { fontSize: 12 },
  popularRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 12,
    gap: 8,
  },
  popularTitle: {
    fontSize: 12,
    fontWeight: "600",
  },
  popularTag: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
  },
  popularTagText: {
    fontSize: 11,
    fontWeight: "600",
  },
});
