import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1 },
  header: { paddingHorizontal: 20, paddingBottom: 28 },
  headerRow: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 4 },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: { fontSize: 22, fontWeight: "800", letterSpacing: -0.4 },
  headerSub: { fontSize: 12, fontWeight: "500", marginTop: 1 },

  scrollView: { marginTop: -12 },
  body: { padding: 16, gap: 14 },

  successWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
    gap: 16,
  },
  successIcon: {
    width: 100,
    height: 100,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  successTitle: { fontSize: 24, fontWeight: "800", textAlign: "center", letterSpacing: -0.4 },
  successSubtitle: { fontSize: 14, textAlign: "center", lineHeight: 22, fontWeight: "500" },

  errorBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FEE2E2",
    borderRadius: 12,
    padding: 12,
  },
  errorText: { fontSize: 13, color: "#DC2626", flex: 1, fontWeight: "500" },

  section: { borderRadius: 18, padding: 18, gap: 12 },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  sectionHint: { fontSize: 12, marginTop: -8, marginBottom: 4 },
  input: { backgroundColor: "transparent" },

  categoryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  catTile: {
    width: "30%",
    alignItems: "center",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 6,
    gap: 6,
    position: "relative",
  },
  catIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  catLabel: { fontSize: 11, fontWeight: "600", textAlign: "center" },
  checkMark: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },

  submitBtn: { borderRadius: 14, marginTop: 4 },
  submitContent: { height: 54 },
  submitLabel: { fontSize: 15, fontWeight: "700", letterSpacing: 0.3 },

  appCard: { borderRadius: 14, padding: 14, gap: 12 },
  appCardHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  appAvatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  appAvatarLetter: { fontSize: 20, fontWeight: "800", color: "#1A56DB" },
  appNameRow: { flex: 1 },
  appBusinessName: { fontSize: 15, fontWeight: "700", marginBottom: 2 },
  appOwnerName: { fontSize: 12, fontWeight: "500" },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusText: { fontSize: 11, fontWeight: "700" },
  appMeta: { flexDirection: "row", alignItems: "center", gap: 5 },
  appMetaText: { fontSize: 12 },
  appDate: { fontSize: 11, fontWeight: "500" },

  tabRow: { flexDirection: "row", gap: 8, paddingHorizontal: 16, paddingVertical: 10 },
  tabChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderWidth: 1.5,
  },
  tabChipText: { fontSize: 12, fontWeight: "700" },
  tabBadge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  tabBadgeText: { fontSize: 10, fontWeight: "800", color: "#FFF" },

  listContent: { padding: 16, gap: 10 },
  emptyWrap: { alignItems: "center", paddingTop: 80, gap: 10 },
  emptyTitle: { fontSize: 18, fontWeight: "700" },
  emptySubtitle: { fontSize: 13, textAlign: "center" },
  centered: { paddingTop: 60, alignItems: "center" },
});
