import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1 },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  headerBlock: {
    paddingHorizontal: 16,
    paddingBottom: 24,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  topNavigationRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    // marginBottom: 0,
  },
  iconCircleButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarOverview: {
    alignItems: "center",
  },
  largeAvatarCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  largeAvatarLetter: {
    fontSize: 32,
    fontWeight: "800",
  },
  businessTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  businessNameText: {
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: -0.4,
    textAlign: "center",
  },
  usernameText: {
    fontSize: 12,
    fontWeight: "500",
    marginTop: 2,
  },
  statusChipsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
    justifyContent: "center",
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  infoSheetContainer: {
    padding: 16,
    gap: 12,
    // marginTop: 4,
  },
  contentCard: {
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.03)",
  },
  cardTitle: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 14,
  },
  categoriesBadgeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  categoryBadgeChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  categoryBadgeText: {
    fontSize: 12,
    fontWeight: "700",
  },
  contactItemRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
  },
  contactItemContent: {
    flex: 1,
    marginLeft: 14,
  },
  contactItemLabel: {
    fontSize: 10,
    fontWeight: "600",
    marginBottom: 1,
  },
  contactItemValue: {
    fontSize: 14,
    fontWeight: "700",
  },
  copyButton: {
    padding: 8,
  },
  cardDivider: {
    height: 1,
    backgroundColor: "rgba(0,0,0,0.05)",
    marginVertical: 4,
  },
  locationItemBlock: {
    gap: 14,
  },
  locationLabelText: {
    fontSize: 10,
    fontWeight: "600",
    marginBottom: 2,
  },
  cityLabelText: {
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 2,
  },
  addressLabelText: {
    fontSize: 13,
    lineHeight: 18,
  },
  mapsActionButton: {
    borderRadius: 12,
    borderWidth: 1.5,
  },
  mapsButtonLabel: {
    fontSize: 13,
    fontWeight: "700",
  },
  notesContainer: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 2,
  },
  notesTextVal: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  floatingFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingTop: 12,
    borderTopWidth: 1,
  },
  footerActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  footerCircleBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  footerSecondaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 12,
    height: 44,
    borderRadius: 22,
  },
  footerSecondaryLabel: {
    fontSize: 12,
    fontWeight: "800",
  },
  footerPrimaryBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    height: 44,
    borderRadius: 22,
  },
  footerPrimaryLabel: {
    color: "#FFF",
    fontSize: 13,
    fontWeight: "800",
  },
});
